services:
  proxy-traefik:
    image: traefik:v3.0.1
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
      # - --entrypoints.web.proxyProtocol.trustedIPs=xxx.xxx.xxx.xxx/32
      # - --entrypoints.web.proxyProtocol.insecure=true
      - --entrypoints.websecure.address=:443
      # - --entrypoints.websecure.proxyProtocol.trustedIPs=xxx.xxx.xxx.xxx/32
      # - --entrypoints.websecure.proxyProtocol.insecure=true
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.letsencrypt.acme.email=some@email.com
      - --certificatesresolvers.letsencrypt.acme.storage=./acme.json
      #- --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      #- --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.tlsChallenge=true
      - --certificatesresolvers.staging-letsencrypt.acme.email=some@email.com
      - --certificatesresolvers.staging-letsencrypt.acme.storage=./acme-staging.json
      - --certificatesresolvers.staging-letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      # - --certificatesresolvers.staging-letsencrypt.acme.httpchallenge=true
      # - --certificatesresolvers.staging-letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.staging-letsencrypt.acme.tlsChallenge=true
      - --api.dashboard=true
      # - --api.insecure=true
      - --providers.file.directory=/traefik/traefik.d
      - --accessLog=true
      - --accessLog.filePath=/traefik/logs/traefik.log
      - --accessLog.bufferingSize=100
    networks:
      - traefik-proxy
    ports:
      - 80:80
      - 443:443
      # - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
      - ./acme-staging.json:/acme-staging.json
      - ./traefik.d:/traefik/traefik.d
      - ./logs/traefik.log:/traefik/logs/traefik.log
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.http.middlewares.httpsonly.redirectscheme.scheme=https"
      - "traefik.http.middlewares.httpsonly.redirectscheme.permanent=false"
      - "traefik.http.routers.httpsonly.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.httpsonly.middlewares=httpsonly"

networks:
  traefik-proxy:
    driver: bridge
    name: traefik
