services:
  portainer:
    image: portainer/portainer-ce:2.20.1
    container_name: portainer
    restart: unless-stopped
    networks:
      - traefik-proxy
    # ports:
    #   - "8000:8000"
    #   - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.portainer-redirect-web-secure.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer-http.rule=Host(`portainer.mydomain.com`)"
      - "traefik.http.routers.portainer-http.entrypoints=web"
      - "traefik.http.routers.portainer-http.middlewares=portainer-redirect-web-secure"
      - "traefik.http.routers.portainer-http.service=portainer-service"
      - "traefik.http.routers.portainer-https.rule=Host(`portainer.mydomain.com`)"
      - "traefik.http.routers.portainer-https.entrypoints=websecure"
      - "traefik.http.routers.portainer-https.tls=true"
      - "traefik.http.routers.portainer-https.tls.domains[0].main=portainer.mydomain.com"
      - "traefik.http.routers.portainer-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portainer-https.middlewares=redirect-http-www@file,redirect-https-www@file"
      - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"

networks:
  traefik-proxy:
    external: true
    name: traefik